version: "3"

services:
  v2ray:
    image: v2fly/v2fly-core:v4.44.0

    ports:
      - "${V2RAY_PORT}:${V2RAY_PORT}/tcp"
      - "${V2RAY_PORT}:${V2RAY_PORT}/udp"
    restart: always
    volumes:
      - "./config.json:/etc/v2ray/config.json"
